name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: make debug
      - name: Check leaks
        run: |
          sudo apt-get install -y valgrind
          valgrind -v --leak-check=full --show-leak-kinds=all ./tests/libft_tester
