name: CI

on:
  push:
    branches: [ test_ci ]
  pull_request:
    branches: [ test_ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: make debug
