# New 42 Norminette is beta
# Workflow will then continue on error

name: 42 Norm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          git clone https://github.com/42School/norminette.git
          cd norminette && pip3 install -r requirements.txt sentry-sdk
          python3 setup.py install
      - name: Check 42 Norm
        run: cd .. && norminette
        continue-on-error: true
